# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@5.0.2

jobs:
  build_and_run_tests:
    docker:
      - image: circleci/node:14.18.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit
      - run:
          name: Run tests with JUnit as reporter
          command: yarn run test:unit:ci --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./
      - store_test_results:
          path: ./

workflows:
  heroku_deploy:
    jobs:
      - build_and_run_tests
      - heroku/deploy-via-git:
          requires:
            - build_and_run_tests
          filters:
            branches:
               only: master
